name: ci

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  lint:
    permissions:
      contents: read
    uses: f2calv/gha-workflows/.github/workflows/lint.yml@v1

  versioning:
    permissions:
      contents: read
    uses: f2calv/gha-workflows/.github/workflows/gha-release-versioning.yml@v1
    with:
      tag-prefix: ''
      tag-and-release: false

  build:
    needs: versioning
    permissions:
      contents: read
    uses: f2calv/gha-workflows/.github/workflows/app-build-dotnet.yml@v1
    with:
      solution-name: event-sourcing-dotnet.slnx
      version: ${{ needs.versioning.outputs.version }}

  release:
    needs: [lint, versioning, build]
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    uses: f2calv/gha-workflows/.github/workflows/gha-release-versioning.yml@v1
    permissions:
      contents: write
    with:
      semVer: ${{ needs.versioning.outputs.version }}
      tag-prefix: ''
      move-major-tag: false
